version: '2'
services:
    rviz_master:
        image: ros:ros-tutorials
        container_name: rviz_master
        environment:
            ROS_HOSTNAME: rviz_master
        command:
            - roscore
    rviz_node:
        image: ros:ros-rviz
        container_name: rviz_node
        environment:
            - "ROS_HOSTNAME: rviz_node"
            - "ROS_MASTER_URI: rviz_master:11311"
            - "DISPLAY: 192.168.99.1:0"
        volumes:
            - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
        command: rosrun rviz rviz
