version: '2'
services:
    rviz_master:
        container_name: rviz_master
        image: ros:ros-tutorials
        environment:
            ROS_HOSTNAME: rviz_master
        command:
            - roscore
    rviz_node:
        container_name: rviz_node
        image: ros:ros-rviz
        environment:
            LIBGL_ALWAYS_SOFTWARE: 1
            QT_X11_NO_MITSHM: 1
            ROS_HOSTNAME: rviz_node
            ROS_MASTER_URI: http://rviz_master:11311
            DISPLAY: ${DISPLAY_ENV}
        volumes:
            - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
        links:
            - rviz_master
        tty: true
        stdin_open: true
        command: bin/bash #rosrun rviz rviz
