version: '2'
services:
    didi_master:
        container_name: didi_master
        image: didi_viacom:ros
        environment:
            ROS_HOSTNAME: didi_master
        command:
            - roscore
    didi_node:
        container_name: didi_node
        image: didi_viacom:ros
        environment:
            ROS_HOSTNAME: didi_node
            ROS_MASTER_URI: http://didi_master:11311
            DISPLAY: ${DISPLAY}
        volumes:
            # link X11 forwarding
            - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
            # link source code directory
            - ~/ros/docker/didi_challenge_ros:/home/didi/catkin_ws/src/didi_ros
            # link data directory
            - ~/ros/data:/home/didi/data
        links:
            - didi_master
        tty: true
        stdin_open: true
        command: bin/bash #rosrun rviz rviz
